export type HeadlineTag = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p';

export type IconClass = | 'black' | 'white' | 'crimson';
export type Icons = | 'apache'
| 'arrow_left'
| 'aws'
| 'calendar'
| 'css'
| 'close'
| 'chevron_down'
| 'chevron_left'
| 'chevron_right'
| 'django'
| 'docker'
| 'education'
| 'flask'
| 'facebook'
| 'gatsby'
| 'google_cloud'
| 'google_login'
| 'graphql'
| 'facebook'
| 'html'
| 'instagram'
| 'javascript'
| 'laravel'
| 'linkedin'
| 'next'
| 'nginx'
| 'nosql'
| 'react'
| 'redux'
| 'sql'
| 'typescript'
| 'work_experience';